// Code generated by entc, DO NOT EDIT.

package reviewer

import (
	"fmt"
	"time"

	"github.com/Xanonymous-GitHub/carnival/db/ent/schema"
)

const (
	// Label holds the string label denoting the reviewer type in the database.
	Label = "reviewer"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldReviewerID holds the string denoting the reviewer_id field in the database.
	FieldReviewerID = "reviewer_id"
	// FieldReviewerName holds the string denoting the reviewer_name field in the database.
	FieldReviewerName = "reviewer_name"
	// FieldIimsRole holds the string denoting the iims_role field in the database.
	FieldIimsRole = "iims_role"
	// FieldCreatedDtime holds the string denoting the created_dtime field in the database.
	FieldCreatedDtime = "created_dtime"
	// Table holds the table name of the reviewer in the database.
	Table = "reviewers"
)

// Columns holds all SQL columns for reviewer fields.
var Columns = []string{
	FieldID,
	FieldReviewerID,
	FieldReviewerName,
	FieldIimsRole,
	FieldCreatedDtime,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// ReviewerIDValidator is a validator for the "reviewer_id" field. It is called by the builders before save.
	ReviewerIDValidator func(string) error
	// ReviewerNameValidator is a validator for the "reviewer_name" field. It is called by the builders before save.
	ReviewerNameValidator func(string) error
	// DefaultCreatedDtime holds the default value on creation for the "created_dtime" field.
	DefaultCreatedDtime func() time.Time
)

// IimsRoleValidator is a validator for the "iims_role" field enum values. It is called by the builders before save.
func IimsRoleValidator(ir schema.IIMSRole) error {
	switch ir {
	case "oav_admin", "oav_reviewer":
		return nil
	default:
		return fmt.Errorf("reviewer: invalid enum value for iims_role field: %q", ir)
	}
}
