// Code generated by entc, DO NOT EDIT.

package applicationstatushistory

import (
	"fmt"
	"time"

	"github.com/Xanonymous-GitHub/carnival/db/ent/schema"
)

const (
	// Label holds the string label denoting the applicationstatushistory type in the database.
	Label = "application_status_history"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldApplicationID holds the string denoting the application_id field in the database.
	FieldApplicationID = "application_id"
	// FieldStatus holds the string denoting the status field in the database.
	FieldStatus = "status"
	// FieldCreatedTime holds the string denoting the created_time field in the database.
	FieldCreatedTime = "created_time"
	// EdgeApplications holds the string denoting the applications edge name in mutations.
	EdgeApplications = "applications"
	// ApplicationFieldID holds the string denoting the ID field of the Application.
	ApplicationFieldID = "application_id"
	// Table holds the table name of the applicationstatushistory in the database.
	Table = "application_status_histories"
	// ApplicationsTable is the table that holds the applications relation/edge.
	ApplicationsTable = "application_status_histories"
	// ApplicationsInverseTable is the table name for the Application entity.
	// It exists in this package in order to avoid circular dependency with the "application" package.
	ApplicationsInverseTable = "applications"
	// ApplicationsColumn is the table column denoting the applications relation/edge.
	ApplicationsColumn = "application_status_histories"
)

// Columns holds all SQL columns for applicationstatushistory fields.
var Columns = []string{
	FieldID,
	FieldApplicationID,
	FieldStatus,
	FieldCreatedTime,
}

// ForeignKeys holds the SQL foreign-keys that are owned by the "application_status_histories"
// table and are not defined as standalone fields in the schema.
var ForeignKeys = []string{
	"application_status_histories",
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	for i := range ForeignKeys {
		if column == ForeignKeys[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultCreatedTime holds the default value on creation for the "created_time" field.
	DefaultCreatedTime func() time.Time
)

// StatusValidator is a validator for the "status" field enum values. It is called by the builders before save.
func StatusValidator(s schema.TicketStatus) error {
	switch s {
	case "created", "replied", "completed":
		return nil
	default:
		return fmt.Errorf("applicationstatushistory: invalid enum value for status field: %q", s)
	}
}
