name: Go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  db-build-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17

    - name: DB server Build
      run: cd db && go build -v ./...

    - name: DB server Test
      run: cd db && go test -v ./...

    - name: DB server Build
      run: cd server && go build -v ./...

    - name: DB server Test
      run: cd server && go test -v ./...
