// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Xanonymous-GitHub/carnival/db/ent/applicationassignmenthistory"
	"github.com/Xanonymous-GitHub/carnival/db/ent/predicate"
)

// ApplicationAssignmentHistoryDelete is the builder for deleting a ApplicationAssignmentHistory entity.
type ApplicationAssignmentHistoryDelete struct {
	config
	hooks    []Hook
	mutation *ApplicationAssignmentHistoryMutation
}

// Where appends a list predicates to the ApplicationAssignmentHistoryDelete builder.
func (aahd *ApplicationAssignmentHistoryDelete) Where(ps ...predicate.ApplicationAssignmentHistory) *ApplicationAssignmentHistoryDelete {
	aahd.mutation.Where(ps...)
	return aahd
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (aahd *ApplicationAssignmentHistoryDelete) Exec(ctx context.Context) (int, error) {
	var (
		err      error
		affected int
	)
	if len(aahd.hooks) == 0 {
		affected, err = aahd.sqlExec(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*ApplicationAssignmentHistoryMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			aahd.mutation = mutation
			affected, err = aahd.sqlExec(ctx)
			mutation.done = true
			return affected, err
		})
		for i := len(aahd.hooks) - 1; i >= 0; i-- {
			if aahd.hooks[i] == nil {
				return 0, fmt.Errorf("ent: uninitialized hook (forgotten import ent/runtime?)")
			}
			mut = aahd.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, aahd.mutation); err != nil {
			return 0, err
		}
	}
	return affected, err
}

// ExecX is like Exec, but panics if an error occurs.
func (aahd *ApplicationAssignmentHistoryDelete) ExecX(ctx context.Context) int {
	n, err := aahd.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (aahd *ApplicationAssignmentHistoryDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := &sqlgraph.DeleteSpec{
		Node: &sqlgraph.NodeSpec{
			Table: applicationassignmenthistory.Table,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: applicationassignmenthistory.FieldID,
			},
		},
	}
	if ps := aahd.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return sqlgraph.DeleteNodes(ctx, aahd.driver, _spec)
}

// ApplicationAssignmentHistoryDeleteOne is the builder for deleting a single ApplicationAssignmentHistory entity.
type ApplicationAssignmentHistoryDeleteOne struct {
	aahd *ApplicationAssignmentHistoryDelete
}

// Exec executes the deletion query.
func (aahdo *ApplicationAssignmentHistoryDeleteOne) Exec(ctx context.Context) error {
	n, err := aahdo.aahd.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{applicationassignmenthistory.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (aahdo *ApplicationAssignmentHistoryDeleteOne) ExecX(ctx context.Context) {
	aahdo.aahd.ExecX(ctx)
}
